### ISSUE TITLE
Same permissions problem

### ISSUE THREAD

**Issue by sumitbounthiyal** [NVIDIA/jetson-gpio#82]
import Jetson.GPIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nvidia/.virtualenvs/cv/lib/python3.5/site-packages/Jetson/GPIO/__init__.py", line 1, in <module>
    from .gpio import *
  File "/home/nvidia/.virtualenvs/cv/lib/python3.5/site-packages/Jetson/GPIO/gpio.py", line 33, in <module>
    raise RuntimeError("The current user does not have permissions set to "
RuntimeError: The current user does not have permissions set to access the library functionalites. Please configure permissions or use the root user to run this

I am having the same problem with the code when I run sample code from File.
Please help me on this.

**Comment by nghungthinh** [comment]
You can run command :
$ sudo python3 your_file.py 

in stead:
$ python3 your_file.py

**Comment by sumitbounthiyal** [comment]
![Uploading 20230329_231144.jpg…]()
Same error is coming with python3 also

**Comment by sumitbounthiyal** [comment]
My problem is similar like #2

**Comment by mdnayeemsardar** [comment]
I am getting the same error. gotta do something... im gonna try rerun this package with its previous version. will let u know when things get working for me.. admin pls respond to this bug

**Comment by anhmiuhv** [comment]
Did you install the udev rules before running the command

**Comment by bhawkins-jpl** [comment]
I did add the user group and install the udev rules, but they didn't seem to work on my Xavier dev board. Changing the rule to
```bash
SUBSYSTEM=="gpio", KERNEL=="gpiochip*", ACTION=="add", \
    GROUP="gpio", MODE="0660"
```
seems to solve the problem. I'm not sure why the shell commands in the provided rule don't work.

**Comment by anhmiuhv** [comment]
Ok I can look into that
